### ISSUE TITLE
run_keybase not in most recent arch package (1.0.48-1)

### ISSUE THREAD

**Issue by cache-return** [keybase/kbfs#1587]
See file list at: https://www.archlinux.org/packages/community/x86_64/keybase/
Consequently(?) kbfs does not work out of the box with this installation method.

**Comment by maxtaco** [comment]
any ideas @oconnor663

**Comment by oconnor663** [comment]
Take a look at our Arch-specific install instructions here: https://keybase.io/docs/the_app/install_linux

There are two distro-official Arch packages, `community/keybase` and `community/kbfs`, which some Arch maintainers are in charge of. You can get KBFS by installing both of those, but you'll be missing the GUI, which in general tends to cause confusing issues. (Like you try to read a shared folder, but your tracking statement with someone else in that folder is broken since they Deleted Facebook, and without the GUI we can't tell you how to fix it.) The Keybase-Inc.-official package is `aur/keybase-bin`. We own that one, and it contains everything.

**Comment by cache-return** [comment]
Kbfs does not work wit the arch packages without some unknown fiddling.  I think the user has to manually enable the systemd services, create /keybase, make an mtab entry for fuse, and maybe more.  Either this should be noted in the install instructions or some version of the run_keybase setup functions should be in the package.

**Comment by oconnor663** [comment]
That's a good point. Ultimately the folks who put those packages together didn't really consult us about doing it, and no one I work with uses anything besides `aur/keybase-bin`. I'll tweak the instructions on that page to make it clear that the `community` packages are very manual.

**Comment by eli-schwartz** [comment]
> the kbfs service, which is, again, autostarted by /usr/bin/keybase

I was mistaken about this I guess, `/usr/bin/keybase` only starts keybase.service which does not actually have a Wants on kbfs.service.

On the other hand, I've just pushed the [keybase-gui package](https://www.archlinux.org/packages/community/x86_64/keybase-gui/), and keybase.gui.service does in fact pull in both keybase and kbfs.

I'm not packaging run_keybase, it's complete overkill and needs patching for several things, so I just dropped in a keybase-gui script which runs electron (and starts the gui service first).
